# Generated by Django 3.1.6 on 2021-11-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211112_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(choices=[('Senior Web Developer', 'Senior Web Developer'), ('Junior Web Developer', 'Junior Web Developer'), ('Designer', 'Designer'), ('Tester', 'Tester')], default='Junior Web Developer', max_length=30),
        ),
    ]
